In [1]:
import data_clean

In [2]:
df = data_clean.cleanit()

The number of rows in the dataframe is: 3313
If this number matches the number of trails in the file, lat/lon split correctly: 3313

If lat/lon appears to have split correctly, enter "y" to continue. Otherwise enter any key to abort:  y

Creating lists for unique features and activities...
List creation complete.

Creating columns in dataframe for unique features...
Column creation and fill complete for features.

Creating columns in dataframe for unique activities...
Column creation and fill complete for activities.

Dropping unncessary features and activities columns.

Wrote new CSV with updated latitude and longitude: /Users/jacobwert/Documents/Data Science/National_Parks/Cleanup Script Test/national_park_trails_rev2.csv

A sample of your cleaned up data:
   trail_id                        name                   area_name  \
0  10020048     Harding Ice Field Trail  Kenai Fjords National Park
1  10236086  Mount Healy Overlook Trail        Denali National Park
2  10267857          Exit Glacier Trail  Kenai Fjords National Park
3  10236076        Horseshoe Lake Trail        Denali National Park
4  10236082          Triple Lakes Trail        Denali National Park

              city_name state_name   country_name  popularity     length  \
0                Seward     Alaska  United States     24.8931  15610.598
1  Denali National Park     Alaska  United States     18.0311   6920.162
2                Seward     Alaska  United States     17.7821   2896.812
3  Denali National Park     Alaska  United States     16.2674   3379.614
4  Denali National Park     Alaska  United States     12.5935  29772.790

   elevation_gain  difficulty_rating  ... snowshoeing  cross-country-skiing  \
0       1161.8976                  5  ...           0                     0
1        507.7968                  3  ...           0                     0
2         81.9912                  1  ...           0                     0
3        119.7864                  1  ...           0                     0
4       1124.7120                  5  ...           0                     0

   fly-fishing  paddle-sports skiing  bike-touring  whitewater-kayaking  \
0            0              0      0             0                    0
1            0              0      0             0                    0
2            0              0      0             0                    0
3            0              0      0             0                    0
4            0              0      0             0                    0

   ice-climbing  surfing  snowboarding
0             0        0             0
1             0        0             0
2             0        0             0
3             0        0             0
4             0        0             0

[5 rows x 64 columns]

In [3]:
df.head()

,trail_id,name,area_name,city_name,state_name,country_name,popularity,length,elevation_gain,difficulty_rating,...,snowshoeing,cross-country-skiing,fly-fishing,paddle-sports,skiing,bike-touring,whitewater-kayaking,ice-climbing,surfing,snowboarding
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Seward,Alaska,United States,24.8931,15610.598,1161.8976,5,...,0,0,0,0,0,0,0,0,0,0
1,10236086,Mount Healy Overlook Trail,Denali National Park,Denali National Park,Alaska,United States,18.0311,6920.162,507.7968,3,...,0,0,0,0,0,0,0,0,0,0
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Seward,Alaska,United States,17.7821,2896.812,81.9912,1,...,0,0,0,0,0,0,0,0,0,0
3,10236076,Horseshoe Lake Trail,Denali National Park,Denali National Park,Alaska,United States,16.2674,3379.614,119.7864,1,...,0,0,0,0,0,0,0,0,0,0
4,10236082,Triple Lakes Trail,Denali National Park,Denali National Park,Alaska,United States,12.5935,29772.790,1124.7120,5,...,0,0,0,0,0,0,0,0,0,0